#! /bin/bash

dataset_name=TriviaQA-web
SOURCE_QA_CKPT_DIR=checkpoints/QA_source_only/

echo "##########################################################################"
echo "Source Only Baseline: Pretrain QA model on SQuAD and test it on $dataset_name"
echo "##########################################################################"

if ! [ -d "$SOURCE_QA_CKPT_DIR" ]; then
  echo "##########################################################################"
  echo "$SOURCE_QA_CKPT_DIR does not exist. Begin Training."
  echo "##########################################################################"
  python QA/run_squad.py \
    --model_type bert \
    --model_name_or_path bert-base-uncased \
    --do_train \
    --do_eval \
    --do_lower_case \
    --train_file data/SQuAD.train.json \
    --predict_file data/"$dataset_name".test.json \
    --per_gpu_train_batch_size 12 \
    --learning_rate 3e-5 \
    --num_train_epochs 3.0 \
    --max_seq_length 384 \
    --threads 24 \
    --per_gpu_eval_batch_size 32 \
    --doc_stride 128 \
    --output_dir $SOURCE_QA_CKPT_DIR \
    --save_steps 10000 \
    --overwrite_cache \
    --overwrite_output_dir
fi

  echo "##########################################################################"
  echo "Train QA model: Source + Target Dev"
  echo "##########################################################################"
  python QA/run_squad.py \
      --model_type bert \
      --model_name_or_path $SOURCE_QA_CKPT_DIR \
      --do_train \
      --do_eval \
      --do_lower_case \
      --train_file data/"$dataset_name".sample.dev.json \
      --predict_file data/"$dataset_name".test.json \
      --per_gpu_train_batch_size 12 \
      --learning_rate 3e-5 \
      --num_train_epochs 3.0 \
      --max_seq_length 384 \
      --threads 24 \
      --per_gpu_eval_batch_size 32 \
      --doc_stride 128 \
      --output_dir checkpoints/QA_"$dataset_name"_Source_TargetDev \
      --save_steps 10000 \
      --overwrite_cache \
      --overwrite_output_dir

  echo "##########################################################################"
  echo "Train QA model: Source + Target Synthetic Data (generated by Finetuned QG)"
  echo "##########################################################################"
  python QA/run_squad.py \
      --model_type bert \
      --model_name_or_path $SOURCE_QA_CKPT_DIR \
      --do_train \
      --do_eval \
      --do_lower_case \
      --train_file data/"$dataset_name"_QG/"$dataset_name".train.targetfinedtuned.gen.json \
      --predict_file data/"$dataset_name".test.json \
      --per_gpu_train_batch_size 12 \
      --learning_rate 3e-5 \
      --num_train_epochs 2.0 \
      --max_seq_length 384 \
      --threads 24 \
      --per_gpu_eval_batch_size 32 \
      --doc_stride 128 \
      --output_dir checkpoints/QA_"$dataset_name"_Source_Sythetic \
      --save_steps 10000 \
      --overwrite_cache \
      --overwrite_output_dir


  echo "##########################################################################"
  echo "Train QA model: Source + Target Synthetic Data (generated by Finetuned QG) + Target Dev"
  echo "##########################################################################"
  python QA/run_squad.py \
      --model_type bert \
      --model_name_or_path checkpoints/QA_"$dataset_name"_Source_Sythetic \
      --do_train \
      --do_eval \
      --do_lower_case \
      --train_file data/"$dataset_name".sample.dev.json \
      --predict_file data/"$dataset_name".test.json \
      --per_gpu_train_batch_size 12 \
      --learning_rate 3e-5 \
      --num_train_epochs 3.0 \
      --max_seq_length 384 \
      --threads 24 \
      --per_gpu_eval_batch_size 32 \
      --doc_stride 128 \
      --output_dir checkpoints/QA_"$dataset_name"_Source_Sythetic_TargetDev \
      --save_steps 10000 \
      --overwrite_cache \
      --overwrite_output_dir
